[package]
name = "dari-winsvc"
description = "The DariService Windows service and its install and uninstall commands"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
repository.workspace = true
license.workspace = true

[[bin]]
name = "dari-service"
path = "src/main.rs"

[target.'cfg(windows)'.dependencies]
windows-service.workspace = true

[lints]
workspace = true
